### ISSUE TITLE
Status check tags are not listed if there are no tags for the parent config

### ISSUE THREAD

**Issue by VicDeo** [little-brother/chupacabra#4]
When tags are not set for the main device section
![screenshot_20170707_125833](https://user-images.githubusercontent.com/991300/27953385-43311d86-6314-11e7-9e51-cd4936da92a2.png)

But are set for individual checks 
![screenshot_20170707_125917](https://user-images.githubusercontent.com/991300/27953390-47166226-6314-11e7-8634-e093ee5c549a.png)

Index page has the only tag `ALL`
![screenshot_20170707_130004](https://user-images.githubusercontent.com/991300/27953400-4da8d60a-6314-11e7-8e9f-ffd14b05990a.png)

**Comment by little-brother** [comment]
This has been fixed in version 0.9
