### ISSUE TITLE
Save as template icon(or button) is missing

### ISSUE THREAD

**Issue by VicDeo** [little-brother/chupacabra#5]
It looks like a rectangle:

![screenshot_20170707_125833](https://user-images.githubusercontent.com/991300/27953468-90ee1ea2-6314-11e7-928c-be2a89fe9b73.png)

**Comment by little-brother** [comment]
What is your OS/browser? Check that page has correct code page (utf-8) and browser don't override it.

**Comment by VicDeo** [comment]
@little-brother openSUSE 42.2 UTF-8 is used system-wide
Chrome 59.0.3071.115 (Official Build)


Recent versions of Chrome  don't allow to set encoding manually. I installed 'Set Character Encoding' extension and force set encoding to UTF8. 
It didn't help.

**Comment by VicDeo** [comment]
Works fine in firefox

**Comment by little-brother** [comment]
This has been fixed in version 0.9.
